/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: icon24.c                                              *
* Font:        宋体                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\STM32\精英板 资料盘(A盘)\精英板 资料盘(A盘)\6，软件资料\3，EMWIN学习资料\STM32Cube_FW_F1_V1.0.0\Middlewares\ST\STemWin\Software\icon.txt*
* Range enabled:        0020 - 0080                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fonticon24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0021[ 17] = { /* code 0021, EXCLAMATION MARK */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0022[ 12] = { /* code 0022, QUOTATION MARK */
  ___XX__X,X_______,
  ___XX__X,X_______,
  __XX__XX,________,
  _XX__XX_,________,
  _X___X__,________,
  X___X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0023[ 34] = { /* code 0023, NUMBER SIGN */
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  __X_____,X_______,
  __X____X,________,
  __X____X,________,
  __X____X,________,
  __X____X,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0024[ 20] = { /* code 0024, DOLLAR SIGN */
  ____X___,
  ____X___,
  __XXXXX_,
  _XX_X_XX,
  XX__X_XX,
  XX__XXXX,
  XX__X___,
  _XX_X___,
  __XXX___,
  ___XXX__,
  ____XXX_,
  ____XXX_,
  ____X_XX,
  XX__X_XX,
  XXX_X_XX,
  XX__X_XX,
  _X__X_X_,
  __XXXX__,
  ____X___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0025[ 34] = { /* code 0025, PERCENT SIGN */
  _XXX____,X_______,
  _X_X____,X_______,
  X___X__X,________,
  X___X__X,________,
  X___X__X,________,
  X___X_X_,________,
  X___X_X_,________,
  _X_XXX__,________,
  _XXX_X_X,XX______,
  _____X_X,_X______,
  ____X_X_,__X_____,
  ____X_X_,__X_____,
  ___X__X_,__X_____,
  ___X__X_,__X_____,
  ___X__X_,__X_____,
  __X____X,_X______,
  __X____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0026[ 34] = { /* code 0026, AMPERSAND */
  ___XXX__,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_X__,________,
  ___XX__X,XXX_____,
  __XXX___,X_______,
  _X_XX___,X_______,
  XX__XX__,X_______,
  XX__XX__,X_______,
  XX___XX_,X_______,
  XX___XXX,________,
  XX____XX,___X____,
  _XX___XX,X__X____,
  __XXXX__,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0027[  6] = { /* code 0027, APOSTROPHE */
  XX______,
  XXX_____,
  __X_____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0028[ 21] = { /* code 0028, LEFT PARENTHESIS */
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ____X___,
  _____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0029[ 21] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_002A[ 24] = { /* code 002A, ASTERISK */
  _____X__,________,
  _____XX_,________,
  _____X__,________,
  XX___X__,_XX_____,
  XXX__X_X,XXX_____,
  ___X_XXX,________,
  ___XXXXX,________,
  XXXX_X_X,XXX_____,
  XX___X__,_XX_____,
  _____X__,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_002B[ 22] = { /* code 002B, PLUS SIGN */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_002C[  6] = { /* code 002C, COMMA */
  XX______,
  XXX_____,
  __X_____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_002D[  2] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_002E[  3] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_002F[ 42] = { /* code 002F, SOLIDUS */
  ________,_X______,
  ________,XX______,
  ________,X_______,
  _______X,X_______,
  _______X,________,
  _______X,________,
  ______X_,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  ____XX__,________,
  ____X___,________,
  ____X___,________,
  ___X____,________,
  ___X____,________,
  __X_____,________,
  __X_____,________,
  _XX_____,________,
  _X______,________,
  XX______,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0030[ 32] = { /* code 0030, DIGIT ZERO */
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0031[ 16] = { /* code 0031, DIGIT ONE */
  ____X___,
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0032[ 32] = { /* code 0032, DIGIT TWO */
  __XXXXX_,________,
  _X____XX,________,
  X______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _______X,X_______,
  _______X,________,
  ______XX,________,
  _____XX_,________,
  ____XX__,________,
  ____X___,________,
  ___X____,________,
  __X_____,X_______,
  _X______,X_______,
  XX______,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0033[ 32] = { /* code 0033, DIGIT THREE */
  __XXXX__,________,
  XX___XX_,________,
  XX____XX,________,
  XX____XX,________,
  ______XX,________,
  ______XX,________,
  _____XX_,________,
  ___XXX__,________,
  ______XX,________,
  _______X,________,
  _______X,X_______,
  _______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0034[ 32] = { /* code 0034, DIGIT FOUR */
  ______XX,________,
  ______XX,________,
  _____XXX,________,
  ____X_XX,________,
  ____X_XX,________,
  ___X__XX,________,
  __X___XX,________,
  __X___XX,________,
  _X____XX,________,
  X_____XX,________,
  XXXXXXXX,XXX_____,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0035[ 32] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,X_______,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  _X_XXXX_,________,
  _XX___XX,________,
  _X_____X,X_______,
  _______X,X_______,
  _______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  X_____XX,________,
  _X____XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0036[ 32] = { /* code 0036, DIGIT SIX */
  ____XXXX,________,
  __XX___X,X_______,
  _XX____X,X_______,
  _XX_____,________,
  _X______,________,
  XX______,________,
  XX__XXXX,________,
  XX_X___X,X_______,
  XXX_____,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _X______,XX______,
  _XX_____,X_______,
  __XX___X,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0037[ 32] = { /* code 0037, DIGIT SEVEN */
  _XXXXXXX,X_______,
  XX_____X,X_______,
  X______X,________,
  X_____X_,________,
  ______X_,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0038[ 32] = { /* code 0038, DIGIT EIGHT */
  __XXXXXX,________,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX_____,X_______,
  _XXX___X,X_______,
  ___XXXX_,________,
  __X__XXX,________,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0039[ 32] = { /* code 0039, DIGIT NINE */
  ___XXXX_,________,
  _XX____X,________,
  _XX____X,X_______,
  XX______,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,XX______,
  _XX___X_,XX______,
  __XXXX__,XX______,
  ________,XX______,
  _______X,X_______,
  _______X,X_______,
  _XX____X,________,
  _XX___XX,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_003A[ 11] = { /* code 003A, COLON */
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_003B[ 14] = { /* code 003B, SEMICOLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_003C[ 34] = { /* code 003C, LESS-THAN SIGN */
  ________,X_______,
  _______X,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ___X____,________,
  __X_____,________,
  _X______,________,
  X_______,________,
  _X______,________,
  __X_____,________,
  ___X____,________,
  ____X___,________,
  _____X__,________,
  ______X_,________,
  _______X,________,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_003D[ 10] = { /* code 003D, EQUALS SIGN */
  XXXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_003E[ 34] = { /* code 003E, GREATER-THAN SIGN */
  X_______,________,
  _X______,________,
  __X_____,________,
  ___X____,________,
  ____X___,________,
  _____X__,________,
  ______X_,________,
  _______X,________,
  ________,X_______,
  _______X,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ___X____,________,
  __X_____,________,
  _X______,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_003F[ 32] = { /* code 003F, QUESTION MARK */
  ___XXXXX,________,
  _XX____X,X_______,
  X_______,XX______,
  X_______,XX______,
  XX______,XX______,
  XX______,XX______,
  ______XX,X_______,
  _____XX_,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0040[ 34] = { /* code 0040, COMMERCIAL AT */
  ____XXX_,________,
  __XX___X,X_______,
  _XX_____,X_______,
  _XX__XXX,_X______,
  _X__XX_X,_X______,
  XX__XX_X,_X______,
  XX__X_XX,_X______,
  XX_XX_X_,_X______,
  XX_XX_X_,_X______,
  XX_XX_X_,_X______,
  XX_XX_X_,_X______,
  XX_XX_X_,X_______,
  _X__XXXX,________,
  _XX_____,_X______,
  _XX_____,X_______,
  __XX___X,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0041[ 32] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XX_,________,
  _____XX_,________,
  ____X_X_,________,
  ____X_XX,________,
  ____X__X,________,
  ____X__X,________,
  ___X___X,________,
  ___X___X,X_______,
  ___X____,X_______,
  ___XXXXX,X_______,
  __X_____,XX______,
  __X_____,XX______,
  __X_____,_X______,
  _X______,_X______,
  _X______,_XX_____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0042[ 32] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXX_,________,
  _XX___XX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX___XX,________,
  _XXXXXX_,________,
  _XX____X,X_______,
  _XX_____,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX____X,X_______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0043[ 32] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,X_______,
  __XX___X,X_______,
  _XX_____,XX______,
  _XX_____,_X______,
  _X______,_X______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,_X______,
  _XX_____,_X______,
  _XX_____,X_______,
  __XX___X,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0044[ 32] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  __XX___X,X_______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,XX______,
  __XX____,XX______,
  __XX___X,X_______,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0045[ 32] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,XX______,
  _XX_____,XX______,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,________,
  _XX____X,________,
  _XX____X,________,
  _XXXXXXX,________,
  _XX____X,________,
  _XX____X,________,
  _XX____X,________,
  _XX_____,________,
  _XX_____,__X_____,
  _XX_____,__X_____,
  _XX_____,_X______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0046[ 32] = { /* code 0046, LATIN CAPITAL LETTER F */
  _XXXXXXX,XXX_____,
  __XX____,_XX_____,
  __XX____,___X____,
  __XX____,___X____,
  __XX____,________,
  __XX____,X_______,
  __XX____,X_______,
  __XXXXXX,X_______,
  __XX____,X_______,
  __XX____,X_______,
  __XX____,X_______,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0047[ 32] = { /* code 0047, LATIN CAPITAL LETTER G */
  ___XXXX_,________,
  __XX___X,________,
  _XX_____,X_______,
  _XX_____,X_______,
  _X______,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX___XXX,XXX_____,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX___X,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0048[ 32] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXXX____,XXXX____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXXXXXX,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_004A[ 38] = { /* code 004A, LATIN CAPITAL LETTER J */
  __XXXXXX,XX______,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  XX___XX_,________,
  XX__XX__,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_004B[ 32] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXXX__XX,XX______,
  _XX____X,X_______,
  _XX___XX,________,
  _XX___X_,________,
  _XX__X__,________,
  _XX_X___,________,
  _XX_XX__,________,
  _XXX_X__,________,
  _XXX_XX_,________,
  _XX___X_,________,
  _XX___XX,________,
  _XX____X,________,
  _XX____X,X_______,
  _XX_____,X_______,
  _XX_____,XX______,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_004C[ 32] = { /* code 004C, LATIN CAPITAL LETTER L */
  _XXXXX__,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,___X____,
  __XX____,___X____,
  __XX____,__X_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_004D[ 32] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_____,XXX_____,
  _XX____X,XX______,
  _XX____X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__X_,XX______,
  _XXX__X_,XX______,
  _X_X__X_,XX______,
  _X_XX_X_,XX______,
  _X_XX_X_,XX______,
  _X_XXX__,XX______,
  _X__XX__,XX______,
  _X__XX__,XX______,
  _X__XX__,XX______,
  _X__X___,XX______,
  XXX____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_004E[ 32] = { /* code 004E, LATIN CAPITAL LETTER N */
  _XXX___X,XXXX____,
  __XX____,_X______,
  __XXX___,_X______,
  __XXX___,_X______,
  __X_XX__,_X______,
  __X_XX__,_X______,
  __X__XX_,_X______,
  __X__XX_,_X______,
  __X___X_,_X______,
  __X___XX,_X______,
  __X____X,_X______,
  __X____X,XX______,
  __X____X,XX______,
  __X_____,XX______,
  __X_____,XX______,
  XXXXX___,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_004F[ 32] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  _XX_____,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX_____,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0050[ 32] = { /* code 0050, LATIN CAPITAL LETTER P */
  _XXXXXXX,X_______,
  __XX____,_XX_____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,__XX____,
  __XX____,XXX_____,
  __XXXXXX,X_______,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0051[ 36] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  _XX_____,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_XXX__,XX______,
  _XX__X__,X_______,
  _XX__XXX,X_______,
  __XX__XX,________,
  ___XXXX_,________,
  ______XX,XX______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0052[ 32] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXXX,X_______,
  _XX_____,XX______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,XX______,
  _XXXXXXX,________,
  _XX___X_,________,
  _XX___XX,________,
  _XX____X,________,
  _XX____X,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,_XX_____,
  XXXX____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0053[ 32] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXXX_,X_______,
  _XX____X,X_______,
  XX______,X_______,
  XX______,X_______,
  XX______,________,
  XXX_____,________,
  _XXXX___,________,
  __XXXXX_,________,
  ____XXXX,X_______,
  ______XX,X_______,
  _______X,XX______,
  X_______,XX______,
  X_______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0054[ 32] = { /* code 0054, LATIN CAPITAL LETTER T */
  _XXXXXXX,XXX_____,
  _X___XX_,__X_____,
  X____XX_,___X____,
  X____XX_,___X____,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0055[ 32] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXXX___X,XX______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  _XX_____,X_______,
  __XX___X,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0056[ 32] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXX____,XXX_____,
  _XX_____,_X______,
  __X_____,X_______,
  __X_____,X_______,
  __XX____,X_______,
  __XX____,X_______,
  ___X___X,________,
  ___X___X,________,
  ___XX__X,________,
  ___XX__X,________,
  ____X_X_,________,
  ____X_X_,________,
  ____XXX_,________,
  ____XX__,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0057[ 32] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXX_XXXX,_XXX____,
  _X___XX_,__X_____,
  _X____X_,__X_____,
  _XX___X_,__X_____,
  _XX___X_,__X_____,
  __X__XX_,_X______,
  __X__XX_,_X______,
  __X__XXX,_X______,
  __X__XXX,_X______,
  __XXX__X,_X______,
  __XXX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___X___X,X_______,
  ___X___X,________,
  ___X___X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0058[ 32] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXXX__XX,XX______,
  _XX____X,________,
  __X____X,________,
  __XX___X,________,
  ___X__X_,________,
  ___XX_X_,________,
  ____XX__,________,
  ____X___,________,
  ____XX__,________,
  ____XX__,________,
  ___X_XX_,________,
  ___X__X_,________,
  __X___XX,________,
  __X____X,________,
  _X_____X,X_______,
  XXX___XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0059[ 32] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXX____,XXXX____,
  _XX_____,__X_____,
  __X_____,_X______,
  __XX____,_X______,
  ___X____,X_______,
  ___XX___,X_______,
  ___XXX_X,________,
  ____XX_X,________,
  ____XXX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_005A[ 32] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XX______,
  _XX_____,X_______,
  XX_____X,X_______,
  X______X,________,
  ______XX,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ___X____,________,
  __XX____,________,
  __X_____,_X______,
  _XX_____,_X______,
  _X______,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_005B[ 21] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXXX___,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_005C[ 40] = { /* code 005C, REVERSE SOLIDUS */
  X_______,________,
  X_______,________,
  _X______,________,
  _X______,________,
  __X_____,________,
  __X_____,________,
  __X_____,________,
  ___X____,________,
  ___X____,________,
  ____X___,________,
  ____X___,________,
  ____XX__,________,
  _____X__,________,
  _____X__,________,
  ______X_,________,
  ______X_,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_005D[ 21] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXXXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_005E[  3] = { /* code 005E, CIRCUMFLEX ACCENT */
  __XX____,
  _X__X___,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0060[  2] = { /* code 0060, GRAVE ACCENT */
  _XX_____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0061[ 22] = { /* code 0061, LATIN SMALL LETTER A */
  ___XXXXX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _______X,X_______,
  ____XXXX,X_______,
  _XXX___X,X_______,
  XXX____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_X_____,
  _XXXXX__,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0062[ 34] = { /* code 0062, LATIN SMALL LETTER B */
  __X_____,________,
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX__XXX,________,
  _XXXX__X,X_______,
  _XXX____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,X_______,
  _XXX___X,X_______,
  _X__XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0063[ 22] = { /* code 0063, LATIN SMALL LETTER C */
  ___XXXX_,________,
  _XX___XX,________,
  _XX___XX,________,
  XX____XX,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,X_______,
  _XX_____,X_______,
  _XX____X,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0064[ 34] = { /* code 0064, LATIN SMALL LETTER D */
  ________,X_______,
  _____XXX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXX_X,X_______,
  _XX___XX,X_______,
  _XX____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _X_____X,X_______,
  _XX___XX,XX______,
  __XXXX_X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0065[ 22] = { /* code 0065, LATIN SMALL LETTER E */
  ___XXXX_,________,
  _XX___XX,________,
  _X_____X,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XXXXXXXX,X_______,
  XX______,________,
  XX______,________,
  _XX_____,X_______,
  _XX____X,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0066[ 32] = { /* code 0066, LATIN SMALL LETTER F */
  _____XXX,X_______,
  ____XX__,XX______,
  ___XX___,XX______,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0067[ 28] = { /* code 0067, LATIN SMALL LETTER G */
  ___XXXXX,XX______,
  __XX_XX_,XX______,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  __XX__XX,________,
  __XXXXX_,________,
  _XX_____,________,
  _XXXXXX_,________,
  _XX__XXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0068[ 34] = { /* code 0068, LATIN SMALL LETTER H */
  __X_____,________,
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_XXXX,________,
  _XXX___X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  XXXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  ___XX___,
  ___XX___,
  ________,
  ________,
  ____X___,
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_006A[ 19] = { /* code 006A, LATIN SMALL LETTER J */
  ____XXX_,
  ____XXX_,
  ________,
  ________,
  ______X_,
  __XXXXX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  XX__XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_006B[ 34] = { /* code 006B, LATIN SMALL LETTER K */
  __X_____,________,
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX___XX,X_______,
  _XX___X_,________,
  _XX___X_,________,
  _XX__X__,________,
  _XX_XX__,________,
  _XXX_X__,________,
  _XX___X_,________,
  _XX___XX,________,
  _XX____X,________,
  _XX____X,X_______,
  XXXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_006C[ 17] = { /* code 006C, LATIN SMALL LETTER L */
  ____X___,
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_006D[ 22] = { /* code 006D, LATIN SMALL LETTER M */
  XXX_XX__,XXX_____,
  _XXX_XXX,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_006E[ 22] = { /* code 006E, LATIN SMALL LETTER N */
  XXX_XXXX,________,
  _XXX___X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  XXXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_006F[ 22] = { /* code 006F, LATIN SMALL LETTER O */
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  _XX____X,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0070[ 28] = { /* code 0070, LATIN SMALL LETTER P */
  XXX_XXXX,________,
  _XXX___X,X_______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX____X,X_______,
  _XXX___X,X_______,
  _XX_XXXX,________,
  _XX_____,________,
  _XX_____,________,
  XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0071[ 28] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXX__,X_______,
  _XX___XX,X_______,
  _XX____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _X_____X,X_______,
  _XX___XX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _______X,X_______,
  _____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0072[ 22] = { /* code 0072, LATIN SMALL LETTER R */
  XXXXX__X,XX______,
  ___XX_X_,_XX_____,
  ___XXX__,_XX_____,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0073[ 11] = { /* code 0073, LATIN SMALL LETTER S */
  __XXXXXX,
  XXX___XX,
  XX_____X,
  XX_____X,
  _XXX____,
  __XXXX__,
  ____XXXX,
  X_____XX,
  X_____XX,
  XX___XXX,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0074[ 30] = { /* code 0074, LATIN SMALL LETTER T */
  ____X___,________,
  ____X___,________,
  ___XX___,________,
  ___XX___,________,
  XXXXXXXX,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,X_______,
  ___XX___,X_______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0075[ 24] = { /* code 0075, LATIN SMALL LETTER U */
  __X_____,X_______,
  XXX___XX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXX__XX,XX______,
  __XXXX_X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0076[ 22] = { /* code 0076, LATIN SMALL LETTER V */
  XXXX___X,XX______,
  _XX_____,X_______,
  __X____X,________,
  __X____X,________,
  __XX___X,________,
  ___X__X_,________,
  ___XX_X_,________,
  ___XX_X_,________,
  ____XX__,________,
  ____XX__,________,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0077[ 22] = { /* code 0077, LATIN SMALL LETTER W */
  XXX_XXXX,_XXX____,
  _X___XX_,__X_____,
  _XX___X_,__X_____,
  __X__XX_,_X______,
  __X__XX_,_X______,
  __XX_XXX,_X______,
  __XXX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0078[ 22] = { /* code 0078, LATIN SMALL LETTER X */
  _XXXX_XX,XX______,
  __XX___X,________,
  ___X___X,________,
  ___XX_X_,________,
  ____XX__,________,
  ____XX__,________,
  ____XXX_,________,
  ___X__X_,________,
  __X____X,________,
  __X____X,X_______,
  XXXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_0079[ 28] = { /* code 0079, LATIN SMALL LETTER Y */
  XXXX__XX,XX______,
  __X____X,________,
  __X____X,________,
  __X____X,________,
  ___X__X_,________,
  ___X__X_,________,
  ___XX_X_,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____X___,________,
  ____X___,________,
  _X__X___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_007A[ 11] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXX_,
  X____XX_,
  X___XX__,
  X___X___,
  ___XX___,
  ___X____,
  __XX____,
  _XX____X,
  _X_____X,
  XX____XX,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_007B[ 21] = { /* code 007B, LEFT CURLY BRACKET */
  ___XX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  X_______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_007C[ 24] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_007D[ 21] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_007E[  8] = { /* code 007E, TILDE */
  _XXX____,________,
  X___X___,_X______,
  X____XX_,_X______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_007F[  1] = { /* code 007F, <control> */
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_4E3B[ 60] = { /* code 4E3B */
  ________,X_______,________,
  ________,_XX_____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,___X____,__X_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,_X______,
  ____XXXX,XXXXXXXX,XXX_____,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,___X____,
  XXXXXXXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_5149[ 63] = { /* code 5149 */
  ________,__XX____,________,
  ________,__XX____,________,
  ____X___,__XX____,X_______,
  _____X__,__XX____,XX______,
  ______X_,__XX___X,X_______,
  ______XX,__XX___X,________,
  _______X,__XX__X_,________,
  ________,__XX__X_,___X____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  _______X,X___XX__,________,
  _______X,X___XX__,________,
  _______X,X___XX__,________,
  _______X,____XX__,________,
  _______X,____XX__,________,
  _______X,____XX__,____X___,
  ______XX,____XX__,____X___,
  ______X_,____XX__,____X___,
  _____X__,____XX__,____X___,
  ____X___,_____X__,____XX__,
  __XX____,_____XXX,XXXXX___,
  XX______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_5173[ 66] = { /* code 5173 */
  ________,______X_,________,
  ______XX,______XX,________,
  _______X,X_____X_,________,
  ________,X____X__,________,
  ________,X____X__,________,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__X_____,________,
  ________,__X_____,___X____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,__X_X___,________,
  ________,_XX_X___,________,
  ________,_X___X__,________,
  ________,XX___XX_,________,
  ________,X_____X_,________,
  _______X,_______X,________,
  ______X_,________,XX______,
  ____XX__,________,_XXX____,
  __XX____,________,__XXXX__,
  _X______,________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_5236[ 66] = { /* code 5236 */
  ______X_,________,___X____,
  ______XX,________,___X____,
  ______X_,________,___X____,
  ___X__X_,________,___X____,
  __XX__X_,__X____X,X__X____,
  __XXXXXX,XXXX___X,___X____,
  __X___X_,_______X,___X____,
  _X____X_,_______X,___X____,
  XXXXXXXX,XXXXX__X,___X____,
  ______X_,_______X,___X____,
  ______X_,_______X,___X____,
  __XXXXXX,XXXX___X,___X____,
  __X___X_,___X___X,___X____,
  __X___X_,___X___X,___X____,
  __X___X_,___X___X,___X____,
  __X___X_,___X___X,___X____,
  __X___X_,___X____,___X____,
  __X___X_,XXXX____,___X____,
  __X___X_,__X_____,___X____,
  ______X_,________,___X____,
  ______X_,________,XXXX____,
  ______X_,________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_526F[ 63] = { /* code 526F */
  ________,___X____,___X____,
  XXXXXXXX,XXXXX___,___X____,
  ________,________,___X____,
  ________,______X_,___X____,
  ___XXXXX,XXX___XX,___X____,
  ___X____,__X___XX,___X____,
  ___X____,__X___XX,___X____,
  ___XXXXX,XXX___XX,___X____,
  ___X____,__X___XX,___X____,
  __X_____,______XX,___X____,
  _XXXXXXX,XXXXX_XX,___X____,
  _X____X_,___X__XX,___X____,
  _X____X_,___X__XX,___X____,
  _X____X_,___X__XX,___X____,
  _XXXXXXX,XXXX__XX,___X____,
  _X____X_,___X____,___X____,
  _X____X_,___X____,___X____,
  _X____X_,___X____,___X____,
  _XXXXXXX,XXXX____,___X____,
  _X______,___X____,XXXX____,
  _X______,________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_5668[ 63] = { /* code 5668 */
  ___XXXXX,X___XXXX,XXX_____,
  ___XX___,XX__XX__,_XX_____,
  ___XX___,XX__XX__,_XX_____,
  ___XX___,XX__XX__,_XX_____,
  ___XX___,XX__XX__,_XX_____,
  ___XXXXX,XX__XXXX,XXX_____,
  ___XX___,XXXXXXXX,_XX_____,
  ___X____,_XX____X,X__X____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,X____X__,________,
  _______X,______X_,________,
  ______X_,_______X,________,
  ____XX__,________,XXX_____,
  ___XXXXX,XX__XXXX,XXXXX___,
  _XX_X___,XX__X___,_XX_____,
  ____X___,XX__X___,_XX_____,
  ____X___,XX__X___,_XX_____,
  ____X___,XX__X___,_XX_____,
  ____XXXX,XX__XXXX,XXX_____,
  ____X___,XX__X___,_XX_____,
  ___X____,X___X___,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_56F4[ 66] = { /* code 56F4 */
  XXXXXXXX,XXXXXXXX,XX______,
  XX______,________,_XX_____,
  XX______,________,_X______,
  XX______,XX______,_X______,
  XX______,X_____X_,_X______,
  XXXXXXXX,XXXXXXXX,_X______,
  XX______,X_______,_X______,
  XX______,X_______,_X______,
  XX__XXXX,XXXXXX__,_X______,
  XX______,X_______,_X______,
  XX______,X_______,_X______,
  XXXXXXXX,XXXXXXX_,_X______,
  XX______,X_____X_,_X______,
  XX______,X_____X_,_X______,
  XX______,X_____X_,_X______,
  XX______,X__XXXX_,_X______,
  XX______,X____X__,_X______,
  XX______,X_______,_X______,
  XX______,X_______,_X______,
  XXXXXXXX,XXXXXXXX,XX______,
  XX______,________,_X______,
  X_______,________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_5F00[ 63] = { /* code 5F00 */
  ________,________,__X_____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _______X,______X_,________,
  _______X,______X_,________,
  _______X,______X_,________,
  _______X,______X_,________,
  _______X,______X_,________,
  _______X,______X_,________,
  _______X,______X_,___X____,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  _______X,______X_,________,
  _______X,______X_,________,
  _______X,______X_,________,
  ______XX,______X_,________,
  ______X_,______X_,________,
  ______X_,______X_,________,
  _____X__,______X_,________,
  ____XX__,______X_,________,
  ___XX___,______X_,________,
  __X_____,______X_,________,
  _X______,______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_63A7[ 66] = { /* code 63A7 */
  ____X___,________,________,
  ____XX__,_____X__,________,
  ____X___,______XX,________,
  ____X___,______X_,________,
  ____X___,_XXXXXXX,XXXXX___,
  XXXXXXXX,_X______,___XX___,
  ____X___,XX__X___,___X____,
  ____X___,____XX_X,X_______,
  ____X___,___XX___,_XX_____,
  ____X__X,__XX____,__XX____,
  ____X_X_,_X______,___X____,
  ___XXX__,X_______,___X____,
  XXX_X___,_XXXXXXX,XXX_____,
  XX__X___,_____XX_,________,
  ____X___,_____XX_,________,
  ____X___,_____XX_,________,
  ____X___,_____XX_,________,
  ____X___,_____XX_,________,
  ____X___,_____XX_,________,
  ____X__X,XXXXXXXX,XXXXX___,
  _XXXX___,________,________,
  ___X____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_6C1B[ 66] = { /* code 6C1B */
  _____X__,________,________,
  ____XX__,________,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ____X___,________,________,
  ___X____,________,________,
  __X___XX,XXXXXXXX,XX______,
  __X_____,________,X_______,
  _X_XXXXX,XXXXXXXX,XX______,
  X_______,________,X_______,
  ______X_,__X_____,X_______,
  _____XX_,__X_____,X_______,
  ____XX__,___X____,X_______,
  ____X___,____X___,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  __X___XX,___X_XX_,XX______,
  _X____X_,___X____,_X______,
  ______X_,___X____,_X______,
  _____XX_,___X____,_X___X__,
  _____X__,___X____,_XX_X___,
  ____X__X,__XX____,__XXX___,
  ___X____,XXX_____,___XXX__,
  _XX_____,_X______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_706F[ 63] = { /* code 706F */
  ____XX__,________,________,
  ____XX__,________,___X____,
  ____XX__,_XXXXXXX,XXXXX___,
  ____XX__,______XX,________,
  ____XX__,X_____XX,________,
  ____XX_X,X_____XX,________,
  _X__XXX_,______XX,________,
  _X__XX__,______XX,________,
  XX__XX__,______XX,________,
  X___XX__,______XX,________,
  ____XX__,______XX,________,
  ____X___,______XX,________,
  ____X___,______XX,________,
  ____XX__,______XX,________,
  ____X_XX,______XX,________,
  ___XX__X,X_____XX,________,
  ___X___X,X_____XX,________,
  ___X____,X_____XX,________,
  __X_____,__XX__XX,________,
  _X______,____XXXX,________,
  X_______,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_7535[ 66] = { /* code 7535 */
  _______X,________,________,
  _______X,________,________,
  _______X,________,________,
  _______X,________,________,
  _______X,________,________,
  XXXXXXXX,XXXXXXXX,________,
  X______X,______X_,________,
  X______X,______X_,________,
  X______X,______X_,________,
  XXXXXXXX,XXXXXXX_,________,
  X______X,______X_,________,
  X______X,______X_,________,
  X______X,______X_,________,
  X______X,______X_,________,
  XXXXXXXX,XXXXXXX_,________,
  X______X,______X_,________,
  X______X,________,________,
  _______X,________,_X______,
  _______X,________,_X______,
  _______X,________,_X______,
  _______X,________,XX______,
  _______X,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_7CFB[ 66] = { /* code 7CFB */
  ________,________,_X______,
  ________,____XXXX,XXX_____,
  ____XXXX,XXXX____,________,
  ________,__XXX___,________,
  ________,_XX_____,________,
  ________,X_______,X_______,
  ______XX,_______X,X_______,
  ____XX_X,XXXXXXX_,________,
  _____XXX,____XX__,________,
  ________,__XX____,________,
  ________,XX______,X_______,
  ______XX,________,_XX_____,
  ___XXX_X,XXXXXXXX,X_XX____,
  ____XXX_,___XX___,__XX____,
  _______X,___XX___,________,
  _______X,___XX_XX,________,
  ______XX,___XX___,XX______,
  _____XX_,___XX___,_XX_____,
  ____X___,___XX___,__XX____,
  __XX___X,X__XX___,___XX___,
  _X______,_XXX____,___X____,
  ________,__X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_7EDF[ 66] = { /* code 7EDF */
  _____X__,_____X__,________,
  _____XX_,______X_,________,
  ____XX__,______XX,________,
  ____X___,_XXXXXXX,XXXXX___,
  ___X____,_____XX_,________,
  ___X___X,X____XX_,________,
  __X____X,____X___,________,
  _XXXXXX_,____X___,_X______,
  _X___X__,___X____,__XX____,
  ____XX__,__X___XX,XXXXX___,
  ___XX___,_XXXXX__,X__XX___,
  ___X____,____XX__,X_______,
  _XX_XXXX,____X___,X_______,
  _XXX____,____X___,X_______,
  ________,____X___,X_______,
  ________,____X___,X_______,
  _____XXX,____X___,X___X___,
  _XXXX___,___XX___,X___X___,
  _XX_____,___X____,X___X___,
  ________,__X_____,X___X___,
  ________,XX______,XXXXX___,
  _______X,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_7F6E[ 60] = { /* code 7F6E */
  ___XXXXX,XXXXXXXX,XXX_____,
  ___X____,X____X__,__X_____,
  ___X____,X____X__,__X_____,
  ___X____,X____X__,__X_____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___X____,__X_____,__X_____,
  ________,__X_____,__X_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,__X_____,X_______,
  _____XXX,XXXXXXXX,XX______,
  _____X__,________,X_______,
  _____X__,________,X_______,
  _____XXX,XXXXXXXX,X_______,
  _____X__,________,X_______,
  _____XXX,XXXXXXXX,X_______,
  _____X__,________,X_______,
  _____XXX,XXXXXXXX,X_______,
  _____X__,________,X_______,
  _____X__,________,X___X___,
  XXXXXXXX,XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fonticon24_8BBE[ 63] = { /* code 8BBE */
  ___X____,__XXXXXX,X_______,
  ____X___,__XX____,XX______,
  ____XX__,__XX____,X_______,
  ____XX__,__XX____,X_______,
  ________,__X_____,X_______,
  ________,__X_____,X_______,
  ________,_X______,X_______,
  XXXXXX__,XX______,XXXXXX__,
  ____X__X,________,_X______,
  ____X_X_,_XXXXXXX,XXX_____,
  ____X___,__X_____,_X______,
  ____X___,___X____,XX______,
  ____X___,___X____,XX______,
  ____X___,____X___,X_______,
  ____X___,X___X__X,________,
  ____X__X,_____XXX,________,
  ____X_X_,_____XX_,________,
  ____XX__,____XX_X,X_______,
  ____XX__,__XX____,XXX_____,
  ________,XX______,__XXX___,
  ______XX,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fonticon24_CharInfo[112] = {
   {   1,   1,   0,  21,  12, acGUI_Fonticon24_0020 } /* code 0020, SPACE */
  ,{   2,  17,   5,   4,  12, acGUI_Fonticon24_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   9,   6,   2,   2,  12, acGUI_Fonticon24_0022 } /* code 0022, QUOTATION MARK */
  ,{  10,  17,   1,   4,  12, acGUI_Fonticon24_0023 } /* code 0023, NUMBER SIGN */
  ,{   8,  20,   2,   3,  12, acGUI_Fonticon24_0024 } /* code 0024, DOLLAR SIGN */
  ,{  11,  17,   0,   4,  12, acGUI_Fonticon24_0025 } /* code 0025, PERCENT SIGN */
  ,{  12,  17,   0,   4,  12, acGUI_Fonticon24_0026 } /* code 0026, AMPERSAND */
  ,{   3,   6,   2,   2,  12, acGUI_Fonticon24_0027 } /* code 0027, APOSTROPHE */
  ,{   6,  21,   5,   2,  12, acGUI_Fonticon24_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   6,  21,   1,   2,  12, acGUI_Fonticon24_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{  11,  12,   1,   6,  12, acGUI_Fonticon24_002A } /* code 002A, ASTERISK */
  ,{  11,  11,   1,   7,  12, acGUI_Fonticon24_002B } /* code 002B, PLUS SIGN */
  ,{   3,   6,   2,  18,  12, acGUI_Fonticon24_002C } /* code 002C, COMMA */
  ,{  10,   1,   1,  12,  12, acGUI_Fonticon24_002D } /* code 002D, HYPHEN-MINUS */
  ,{   3,   3,   2,  18,  12, acGUI_Fonticon24_002E } /* code 002E, FULL STOP */
  ,{  10,  21,   1,   2,  12, acGUI_Fonticon24_002F } /* code 002F, SOLIDUS */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  16,   2,   5,  12, acGUI_Fonticon24_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  16,   1,   5,  12, acGUI_Fonticon24_0032 } /* code 0032, DIGIT TWO */
  ,{   9,  16,   1,   5,  12, acGUI_Fonticon24_0033 } /* code 0033, DIGIT THREE */
  ,{  11,  16,   1,   5,  12, acGUI_Fonticon24_0034 } /* code 0034, DIGIT FOUR */
  ,{   9,  16,   1,   5,  12, acGUI_Fonticon24_0035 } /* code 0035, DIGIT FIVE */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  16,   2,   5,  12, acGUI_Fonticon24_0037 } /* code 0037, DIGIT SEVEN */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_0038 } /* code 0038, DIGIT EIGHT */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_0039 } /* code 0039, DIGIT NINE */
  ,{   3,  11,   5,  10,  12, acGUI_Fonticon24_003A } /* code 003A, COLON */
  ,{   2,  14,   5,  10,  12, acGUI_Fonticon24_003B } /* code 003B, SEMICOLON */
  ,{   9,  17,   2,   4,  12, acGUI_Fonticon24_003C } /* code 003C, LESS-THAN SIGN */
  ,{  10,   5,   1,  10,  12, acGUI_Fonticon24_003D } /* code 003D, EQUALS SIGN */
  ,{   9,  17,   2,   4,  12, acGUI_Fonticon24_003E } /* code 003E, GREATER-THAN SIGN */
  ,{  10,  16,   2,   5,  12, acGUI_Fonticon24_003F } /* code 003F, QUESTION MARK */
  ,{  10,  17,   1,   4,  12, acGUI_Fonticon24_0040 } /* code 0040, COMMERCIAL AT */
  ,{  12,  16,   0,   5,  12, acGUI_Fonticon24_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  11,  16,   0,   5,  12, acGUI_Fonticon24_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  11,  16,   0,   5,  12, acGUI_Fonticon24_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  12,  16,  -1,   5,  12, acGUI_Fonticon24_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  11,  16,   1,   5,  12, acGUI_Fonticon24_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  12,  16,   0,   5,  12, acGUI_Fonticon24_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   8,  16,   2,   5,  12, acGUI_Fonticon24_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  10,  19,   1,   5,  12, acGUI_Fonticon24_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  11,  16,   0,   5,  12, acGUI_Fonticon24_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{  12,  16,  -1,   5,  12, acGUI_Fonticon24_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  11,  16,   0,   5,  12, acGUI_Fonticon24_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  12,  16,   0,   5,  12, acGUI_Fonticon24_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  12,  16,  -1,   5,  12, acGUI_Fonticon24_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  10,  18,   1,   5,  12, acGUI_Fonticon24_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  12,  16,   0,   5,  12, acGUI_Fonticon24_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  12,  16,   0,   5,  12, acGUI_Fonticon24_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  11,  16,   0,   5,  12, acGUI_Fonticon24_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  12,  16,   0,   5,  12, acGUI_Fonticon24_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  12,  16,   0,   5,  12, acGUI_Fonticon24_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   5,  21,   5,   2,  12, acGUI_Fonticon24_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   9,  20,   2,   4,  12, acGUI_Fonticon24_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   5,  21,   2,   2,  12, acGUI_Fonticon24_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   6,   3,   3,   1,  12, acGUI_Fonticon24_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{  12,   1,   0,  23,  12, acGUI_Fonticon24_005F } /* code 005F, LOW LINE */
  ,{   5,   2,   2,   2,  12, acGUI_Fonticon24_0060 } /* code 0060, GRAVE ACCENT */
  ,{  11,  11,   1,  10,  12, acGUI_Fonticon24_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{  10,  17,   1,   4,  12, acGUI_Fonticon24_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   9,  11,   1,  10,  12, acGUI_Fonticon24_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{  10,  17,   1,   4,  12, acGUI_Fonticon24_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   9,  11,   2,  10,  12, acGUI_Fonticon24_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{  10,  16,   1,   5,  12, acGUI_Fonticon24_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{  10,  14,   1,  10,  12, acGUI_Fonticon24_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{  10,  17,   1,   4,  12, acGUI_Fonticon24_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   8,  16,   2,   5,  12, acGUI_Fonticon24_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   7,  19,   2,   5,  12, acGUI_Fonticon24_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  10,  17,   1,   4,  12, acGUI_Fonticon24_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   8,  17,   2,   4,  12, acGUI_Fonticon24_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  12,  11,   0,  10,  12, acGUI_Fonticon24_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{  10,  11,   1,  10,  12, acGUI_Fonticon24_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  10,  11,   1,  10,  12, acGUI_Fonticon24_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{  10,  14,   1,  10,  12, acGUI_Fonticon24_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{  10,  14,   1,  10,  12, acGUI_Fonticon24_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{  11,  11,   0,  10,  12, acGUI_Fonticon24_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   8,  11,   2,  10,  12, acGUI_Fonticon24_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   9,  15,   1,   6,  12, acGUI_Fonticon24_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  10,  12,   1,   9,  12, acGUI_Fonticon24_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  10,  11,   1,  10,  12, acGUI_Fonticon24_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  12,  11,   0,  10,  12, acGUI_Fonticon24_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  10,  11,   1,  10,  12, acGUI_Fonticon24_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{  10,  14,   1,  10,  12, acGUI_Fonticon24_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   8,  11,   2,  10,  12, acGUI_Fonticon24_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   5,  21,   5,   2,  12, acGUI_Fonticon24_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  24,   6,   0,  12, acGUI_Fonticon24_007C } /* code 007C, VERTICAL LINE */
  ,{   5,  21,   2,   2,  12, acGUI_Fonticon24_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{  10,   4,   1,   1,  12, acGUI_Fonticon24_007E } /* code 007E, TILDE */
  ,{   1,   1,   0,  21,  12, acGUI_Fonticon24_007F } /* code 007F, <control> */
  ,{  22,  20,   1,   2,  24, acGUI_Fonticon24_4E3B } /* code 4E3B */
  ,{  22,  21,   1,   2,  24, acGUI_Fonticon24_5149 } /* code 5149 */
  ,{  22,  22,   1,   1,  24, acGUI_Fonticon24_5173 } /* code 5173 */
  ,{  21,  22,   1,   1,  24, acGUI_Fonticon24_5236 } /* code 5236 */
  ,{  21,  21,   1,   2,  24, acGUI_Fonticon24_526F } /* code 526F */
  ,{  22,  21,   1,   2,  24, acGUI_Fonticon24_5668 } /* code 5668 */
  ,{  19,  22,   3,   1,  24, acGUI_Fonticon24_56F4 } /* code 56F4 */
  ,{  22,  21,   1,   2,  24, acGUI_Fonticon24_5F00 } /* code 5F00 */
  ,{  22,  22,   1,   1,  24, acGUI_Fonticon24_63A7 } /* code 63A7 */
  ,{  22,  22,   1,   1,  24, acGUI_Fonticon24_6C1B } /* code 6C1B */
  ,{  22,  21,   1,   2,  24, acGUI_Fonticon24_706F } /* code 706F */
  ,{  19,  22,   4,   1,  24, acGUI_Fonticon24_7535 } /* code 7535 */
  ,{  21,  22,   1,   1,  24, acGUI_Fonticon24_7CFB } /* code 7CFB */
  ,{  22,  22,   1,   1,  24, acGUI_Fonticon24_7EDF } /* code 7EDF */
  ,{  22,  20,   1,   2,  24, acGUI_Fonticon24_7F6E } /* code 7F6E */
  ,{  22,  21,   1,   2,  24, acGUI_Fonticon24_8BBE } /* code 8BBE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop17 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fonticon24_CharInfo[111] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop16 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_Fonticon24_CharInfo[110] /* address of first character */
  ,&GUI_Fonticon24_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop15 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_Fonticon24_CharInfo[109] /* address of first character */
  ,&GUI_Fonticon24_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop14 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_Fonticon24_CharInfo[108] /* address of first character */
  ,&GUI_Fonticon24_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop13 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fonticon24_CharInfo[107] /* address of first character */
  ,&GUI_Fonticon24_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop12 = {
   0x706F /* first character */
  ,0x706F /* last character  */
  ,&GUI_Fonticon24_CharInfo[106] /* address of first character */
  ,&GUI_Fonticon24_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop11 = {
   0x6C1B /* first character */
  ,0x6C1B /* last character  */
  ,&GUI_Fonticon24_CharInfo[105] /* address of first character */
  ,&GUI_Fonticon24_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop10 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_Fonticon24_CharInfo[104] /* address of first character */
  ,&GUI_Fonticon24_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop9 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_Fonticon24_CharInfo[103] /* address of first character */
  ,&GUI_Fonticon24_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop8 = {
   0x56F4 /* first character */
  ,0x56F4 /* last character  */
  ,&GUI_Fonticon24_CharInfo[102] /* address of first character */
  ,&GUI_Fonticon24_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop7 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_Fonticon24_CharInfo[101] /* address of first character */
  ,&GUI_Fonticon24_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop6 = {
   0x526F /* first character */
  ,0x526F /* last character  */
  ,&GUI_Fonticon24_CharInfo[100] /* address of first character */
  ,&GUI_Fonticon24_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop5 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_Fonticon24_CharInfo[ 99] /* address of first character */
  ,&GUI_Fonticon24_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop4 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_Fonticon24_CharInfo[ 98] /* address of first character */
  ,&GUI_Fonticon24_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop3 = {
   0x5149 /* first character */
  ,0x5149 /* last character  */
  ,&GUI_Fonticon24_CharInfo[ 97] /* address of first character */
  ,&GUI_Fonticon24_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop2 = {
   0x4E3B /* first character */
  ,0x4E3B /* last character  */
  ,&GUI_Fonticon24_CharInfo[ 96] /* address of first character */
  ,&GUI_Fonticon24_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonticon24_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_Fonticon24_CharInfo[  0] /* address of first character */
  ,&GUI_Fonticon24_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fonticon24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fonticon24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

