/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: jujia24.c                                             *
* Font:        宋体                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\新建文本文档.txt *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontjujia24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontjujia24_5BB6[ 72] = { /* code 5BB6 */
  ________,________,________,
  ________,__XX____,________,
  ________,___XX___,________,
  ____X___,____X___,________,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ___XX___,________,____X___,
  __XX____,________,___X____,
  _____XXX,XXXXXXXX,XX______,
  ________,__X_____,________,
  ________,_XX_____,________,
  ________,X__X____,_XX_____,
  ______XX,___XX__X,X_______,
  ____XX__,__XXX_XX,________,
  __XX____,_X___X_X,________,
  _______X,X___XX__,X_______,
  ______X_,___XXX__,X_______,
  ____XX__,__XX_XX_,_X______,
  __XX____,_XX__XX_,_XX_____,
  ________,X____XX_,__XXX___,
  ______XX,_____XX_,___XXX__,
  ___XXX__,_____X__,________,
  _XX_____,__XXXX__,________,
  ________,___XX___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontjujia24_5C45[ 72] = { /* code 5C45 */
  ________,________,________,
  ________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XX__,________,___XX___,
  ____XX__,________,___X____,
  ____XX__,________,___X____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XX__,________,___X____,
  ____XX__,_____XX_,________,
  ____XX__,_____X__,________,
  ____XX__,_____X__,________,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ____XX__,_____X__,________,
  ____XX__,_____X__,________,
  ____X___,_____X__,__X_____,
  ____X___,XXXXXXXX,XXXX____,
  ____X___,X_______,__X_____,
  ____X___,X_______,__X_____,
  ___X____,X_______,__X_____,
  ___X____,X_______,__X_____,
  __X_____,XXXXXXXX,XXX_____,
  __X_____,X_______,__X_____,
  _X______,X_______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontjujia24_636E[ 72] = { /* code 636E */
  ________,________,________,
  ________,________,________,
  _____X__,________,________,
  _____XX_,__XXXXXX,XXXXX___,
  _____X__,__XX____,___XX___,
  _____X__,__XX____,___XX___,
  _____X__,X_XX____,___XX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _____X__,__XX____,X__XX___,
  _____X__,__X_____,X_______,
  _____X__,_XX_____,X_______,
  _____X_X,X_XXXXXX,XXXXXX__,
  _____XX_,__X_____,X_______,
  ____XX__,__X_____,X_______,
  _XXX_X__,__X_____,X_______,
  __X__X__,_XX_XXXX,XXXXX___,
  _____X__,_X__X___,___XX___,
  _____X__,_X__X___,___XX___,
  _____X__,X___X___,___XX___,
  _____X__,X___X___,___XX___,
  _____X_X,____XXXX,XXXXX___,
  __XXXXX_,____X___,___XX___,
  ____XX__,____X___,___X____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontjujia24_6570[ 72] = { /* code 6570 */
  ________,________,________,
  _______X,_______X,________,
  ___X___X,___X___X,X_______,
  ____X__X,___X___X,________,
  ____XX_X,__X___XX,________,
  ____X__X,_X____X_,________,
  __XXXXXX,XXXXX_XX,XXXXXX__,
  ______XX,_____XX_,___X____,
  _____XXX,XX___XX_,___X____,
  _____X_X,__X__XX_,___X____,
  ____X__X,__XXX_X_,__XX____,
  __XX___X,____X_X_,__XX____,
  _X_____X,_______X,__XX____,
  ______XX,_______X,__X_____,
  _XXXXXXX,XXXX___X,__X_____,
  _____XX_,__X____X,XXX_____,
  _____X__,__X_____,XX______,
  ____XXX_,_X______,XX______,
  _______X,XXX____X,XXX_____,
  _______X,X_XX__XX,__XX____,
  _____XX_,___X_XX_,___XXX__,
  ___XX___,___XX___,____XX__,
  _XX_____,__X_____,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontjujia24_CharInfo[4] = {
   {  24,  24,  3, acGUI_Fontjujia24_5BB6 } /* code 5BB6 */
  ,{  24,  24,  3, acGUI_Fontjujia24_5C45 } /* code 5C45 */
  ,{  24,  24,  3, acGUI_Fontjujia24_636E } /* code 636E */
  ,{  24,  24,  3, acGUI_Fontjujia24_6570 } /* code 6570 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontjujia24_Prop4 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_Fontjujia24_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontjujia24_Prop3 = {
   0x636E /* first character */
  ,0x636E /* last character  */
  ,&GUI_Fontjujia24_CharInfo[  2] /* address of first character */
  ,&GUI_Fontjujia24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontjujia24_Prop2 = {
   0x5C45 /* first character */
  ,0x5C45 /* last character  */
  ,&GUI_Fontjujia24_CharInfo[  1] /* address of first character */
  ,&GUI_Fontjujia24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontjujia24_Prop1 = {
   0x5BB6 /* first character */
  ,0x5BB6 /* last character  */
  ,&GUI_Fontjujia24_CharInfo[  0] /* address of first character */
  ,&GUI_Fontjujia24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontjujia24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontjujia24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

