/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: shuju_anniu40.c                                       *
* Font:        宋体                                                  *
* Height:      40                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  40                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\新建文本文档.txt *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontshuju_anniu40;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontshuju_anniu40_56DE[200] = { /* code 56DE */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  _____XX_,________,________,________,_X______,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,________,________,________,XXX_____,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XXX,XXXXXXXX,XXXX____,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XXX,XXXXXXXX,XXX_____,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XX_,________,_XX_____,XX______,
  ______XX,_____XX_,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XX______,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,________,________,________,XX______,
  ______XX,________,________,________,XXX_____,
  ______XX,________,________,________,XX______,
  _____XX_,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontshuju_anniu40_8FD4[200] = { /* code 8FD4 */
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,_______X,________,
  ______XX,________,________,_____XXX,X_______,
  _______X,X_______,________,_XXXXXXX,XX______,
  ________,XX______,XX_XXXXX,XXX_____,________,
  ________,XXX_____,XXX_____,________,________,
  ________,XXX_____,XX______,________,________,
  ________,_XX_____,XX______,________,________,
  ________,_X______,XX______,________,________,
  ________,________,XX______,________,________,
  ________,________,XX______,________,________,
  ________,________,XX______,_______X,X_______,
  ________,________,XXXXXXXX,XXXXXXXX,XX______,
  ________,_XX_____,XX______,______XX,X_______,
  __XXXXXX,XXXX____,XX______,______XX,________,
  ________,XXX_____,XX______,______XX,________,
  ________,XX______,XX______,_____XX_,________,
  ________,XX______,XX__X___,_____XX_,________,
  ________,XX______,XX___XX_,____XX__,________,
  ________,XX______,XX____XX,X___XX__,________,
  ________,XX______,XX______,XXXXX___,________,
  ________,XX_____X,X_______,_XXXX___,________,
  ________,XX_____X,X_______,__XXXX__,________,
  ________,XX_____X,X_______,_XX_XXX_,________,
  ________,XX____XX,________,XX___XXX,X_______,
  ________,XX____XX,_______X,X_____XX,XX______,
  ________,XX___XX_,______XX,_______X,XXX_____,
  ________,XX___X__,_____XX_,________,XXX_____,
  ________,XX__X___,___XX___,________,_XX_____,
  ________,XX______,__XX____,________,__X_____,
  ______XX,X_XX____,XX______,________,________,
  _____XX_,___XX___,________,________,________,
  ___XXX__,_____XXX,________,________,________,
  __XXXX__,______XX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ___XX___,________,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,________,____XXXX,XXXXXXXX,XXX_____,
  ________,________,________,________,________,
  ________,________,________,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontshuju_anniu40_CharInfo[2] = {
   {  40,  40,  5, acGUI_Fontshuju_anniu40_56DE } /* code 56DE */
  ,{  40,  40,  5, acGUI_Fontshuju_anniu40_8FD4 } /* code 8FD4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontshuju_anniu40_Prop2 = {
   0x8FD4 /* first character */
  ,0x8FD4 /* last character  */
  ,&GUI_Fontshuju_anniu40_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontshuju_anniu40_Prop1 = {
   0x56DE /* first character */
  ,0x56DE /* last character  */
  ,&GUI_Fontshuju_anniu40_CharInfo[  0] /* address of first character */
  ,&GUI_Fontshuju_anniu40_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontshuju_anniu40 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,40 /* height of font  */
  ,40 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontshuju_anniu40_Prop1}
  ,34 /* Baseline */
  ,18 /* Height of lowercase characters */
  ,27 /* Height of capital characters */
};

