/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: sonti24.c                                             *
* Font:        宋体                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\STM32\精英板 资料盘(A盘)\精英板 资料盘(A盘)\6，软件资料\3，EMWIN学习资料\STM32Cube_FW_F1_V1.0.0\Middlewares\ST\STemWin\Software\Chinese.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsonti24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_002D[ 48] = { /* code 002D, HYPHEN-MINUS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_0043[ 48] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XXX,XX______,
  ___XX___,XX______,
  __XX____,_XX_____,
  __XX____,__X_____,
  __X_____,__X_____,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,__X_____,
  __XX____,__X_____,
  __XX____,_X______,
  ___XX___,XX______,
  ____XXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_0061[ 48] = { /* code 0061, LATIN SMALL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  __XX____,XX______,
  __XX____,XX______,
  ________,XX______,
  _____XXX,XX______,
  __XXX___,XX______,
  _XXX____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XXX___X,XX_X____,
  __XXXXX_,_XXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_0065[ 48] = { /* code 0065, LATIN SMALL LETTER E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XXX,X_______,
  ___XX___,XX______,
  ___X____,_X______,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XXXXXX,XXX_____,
  __XX____,________,
  __XX____,________,
  ___XX___,__X_____,
  ___XX___,_X______,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_006E[ 48] = { /* code 006E, LATIN SMALL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX_XXX,X_______,
  __XXX___,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  _XXXX__X,XXX_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_006F[ 48] = { /* code 006F, LATIN SMALL LETTER O */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,________,
  ___XX__X,X_______,
  __XX____,XX______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  __XX____,XX______,
  __XX____,XX______,
  ____XXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_0070[ 48] = { /* code 0070, LATIN SMALL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX_XXX,X_______,
  __XXX___,XX______,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,XX______,
  __XXX___,XX______,
  __XX_XXX,X_______,
  __XX____,________,
  __XX____,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_0073[ 48] = { /* code 0073, LATIN SMALL LETTER S */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XX______,
  __XXX___,XX______,
  __XX____,_X______,
  __XX____,_X______,
  ___XXX__,________,
  ____XXXX,________,
  ______XX,XX______,
  __X_____,XX______,
  __X_____,XX______,
  __XX___X,XX______,
  __XXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_0074[ 48] = { /* code 0074, LATIN SMALL LETTER T */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  ____XX__,________,
  ____XX__,________,
  _XXXXXXX,X_______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,_X______,
  ____XX__,_X______,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_5BB6[ 72] = { /* code 5BB6 */
  ________,________,________,
  ________,__XX____,________,
  ________,___XX___,________,
  ____X___,____X___,________,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ___XX___,________,____X___,
  __XX____,________,___X____,
  _____XXX,XXXXXXXX,XX______,
  ________,__X_____,________,
  ________,_XX_____,________,
  ________,X__X____,_XX_____,
  ______XX,___XX__X,X_______,
  ____XX__,__XXX_XX,________,
  __XX____,_X___X_X,________,
  _______X,X___XX__,X_______,
  ______X_,___XXX__,X_______,
  ____XX__,__XX_XX_,_X______,
  __XX____,_XX__XX_,_XX_____,
  ________,X____XX_,__XXX___,
  ______XX,_____XX_,___XXX__,
  ___XXX__,_____X__,________,
  _XX_____,__XXXX__,________,
  ________,___XX___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_5C45[ 72] = { /* code 5C45 */
  ________,________,________,
  ________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XX__,________,___XX___,
  ____XX__,________,___X____,
  ____XX__,________,___X____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XX__,________,___X____,
  ____XX__,_____XX_,________,
  ____XX__,_____X__,________,
  ____XX__,_____X__,________,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ____XX__,_____X__,________,
  ____XX__,_____X__,________,
  ____X___,_____X__,__X_____,
  ____X___,XXXXXXXX,XXXX____,
  ____X___,X_______,__X_____,
  ____X___,X_______,__X_____,
  ___X____,X_______,__X_____,
  ___X____,X_______,__X_____,
  __X_____,XXXXXXXX,XXX_____,
  __X_____,X_______,__X_____,
  _X______,X_______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_667A[ 72] = { /* code 667A */
  ________,________,________,
  _____X__,________,________,
  _____X__,________,________,
  ____XXXX,XXXX__XX,XXXXX___,
  ____X___,X_____X_,____X___,
  ___X____,X_____X_,____X___,
  ___X___X,X_____X_,____X___,
  __XXXXXX,XXXXXXX_,____X___,
  _______X,______X_,____X___,
  _______X,XX____X_,____X___,
  ______XX,__XX__XX,XXXXX___,
  _____XX_,___XX_X_,____X___,
  ____XX__,___X__X_,________,
  ___X___X,XXXXXXXX,XXX_____,
  __X____X,________,_X______,
  _______X,________,_X______,
  _______X,XXXXXXXX,XX______,
  _______X,________,_X______,
  _______X,________,_X______,
  _______X,________,_X______,
  _______X,XXXXXXXX,XXX_____,
  _______X,________,_XX_____,
  ________,________,_X______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_7A0B[ 72] = { /* code 7A0B */
  ________,________,________,
  ________,________,________,
  ________,X_______,________,
  _____XXX,XX_XXXXX,XXXXX___,
  __XXX_X_,____X___,____X___,
  ______X_,____X___,____X___,
  ______X_,____X___,____X___,
  ______X_,____X___,____X___,
  _XXXXXXX,XXX_XXXX,XXXXX___,
  _____XX_,___XX___,____X___,
  _____XX_,___X____,____X___,
  _____XXX,__XXXXXX,XXXXXX__,
  ____X_X_,XX______,X_______,
  ____X_X_,_X______,X_______,
  ___XX_X_,________,X_______,
  ___X__X_,________,X___X___,
  __X___X_,___XXXXX,XXXXXX__,
  __X___X_,________,X_______,
  _X____X_,________,X_______,
  _____XX_,________,X_______,
  _____XX_,________,X____X__,
  _____XX_,_XXXXXXX,XXXXXXX_,
  _____XX_,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_80FD[ 72] = { /* code 80FD */
  ________,________,________,
  ______X_,________,________,
  ______XX,______XX,________,
  _____XX_,______X_,___X____,
  _____X__,_X____X_,__XXX___,
  ____X___,__X___X_,_XX_____,
  __XX____,XXXX__XX,X_______,
  __XXXXXX,___X__X_,________,
  ________,___X__X_,_____X__,
  ___XXXXX,XXX___X_,_____X__,
  ___XX___,_XX___XX,XXXXXX__,
  ___XX___,_XX_____,________,
  ___XXXXX,XXX__X__,________,
  ___XX___,_XX___X_,___X____,
  ___XX___,_XX___X_,__XXX___,
  ___XX___,_XX___X_,_XX_____,
  ___XXXXX,XXX___XX,X_______,
  ___XX___,_XX___X_,_____X__,
  ___XX___,_XX___X_,_____X__,
  ___XX___,_XX___X_,_____X__,
  ___XX___,_XX___X_,_____XX_,
  ___XX__X,XXX___XX,XXXXXX__,
  ___X____,_X______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_8BA1[ 72] = { /* code 8BA1 */
  ________,________,________,
  ________,________,________,
  ____X___,______X_,________,
  _____XX_,______XX,________,
  ______X_,______XX,________,
  ______X_,______XX,________,
  ________,______XX,________,
  ________,______XX,________,
  ________,______XX,________,
  _XXXXXX_,______XX,_____X__,
  _____X__,XXXXXXXX,XXXXXX__,
  _____X__,______XX,________,
  _____X__,______XX,________,
  _____X__,______XX,________,
  _____X__,______XX,________,
  _____X__,______XX,________,
  _____X__,_X____XX,________,
  _____X__,X_____XX,________,
  _____X_X,______XX,________,
  _____XXX,______XX,________,
  _____XX_,______XX,________,
  ________,______XX,________,
  ________,______XX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_8BBE[ 72] = { /* code 8BBE */
  ________,________,________,
  ________,________,________,
  ____X___,___XXXXX,XX______,
  _____X__,___XX___,_XX_____,
  _____XX_,___XX___,_X______,
  _____XX_,___XX___,_X______,
  ________,___X____,_X______,
  ________,___X____,_X______,
  ________,__X_____,_X______,
  _XXXXXX_,_XX_____,_XXXXXX_,
  _____X__,X_______,__X_____,
  _____X_X,__XXXXXX,XXXX____,
  _____X__,___X____,__X_____,
  _____X__,____X___,_XX_____,
  _____X__,____X___,_XX_____,
  _____X__,_____X__,_X______,
  _____X__,_X___X__,X_______,
  _____X__,X_____XX,X_______,
  _____X_X,______XX,________,
  _____XX_,_____XX_,XX______,
  _____XX_,___XX___,_XXX____,
  ________,_XX_____,___XXX__,
  _______X,X_______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsonti24_8BFE[ 72] = { /* code 8BFE */
  ________,________,________,
  ________,________,________,
  ________,__XXXXXX,XXXX____,
  ___XX___,__X___XX,___XX___,
  ____XX__,__X___XX,___X____,
  _____X__,__X___XX,___X____,
  ________,__XXXXXX,XXXX____,
  ________,__X___XX,___X____,
  ________,__X___XX,___X____,
  _XXXXX__,__X___XX,___X____,
  ____X___,__XXXXXX,XXXX____,
  ____X___,__X___XX,___X____,
  ____X___,______XX,_____X__,
  ____X__X,XXXXXXXX,XXXXXX__,
  ____X___,_____XXX,________,
  ____X___,_X___XXX,X_______,
  ____X___,X___X_XX,_X______,
  ____X__X,___X__XX,_XX_____,
  ____X_X_,__X___XX,__XX____,
  ____XX__,_X____XX,___XXX__,
  ____XX_X,X_____XX,____XX__,
  ______X_,______XX,________,
  ________,______X_,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsonti24_CharInfo[17] = {
   {  12,  12,  2, acGUI_Fontsonti24_002D } /* code 002D */
  ,{  12,  12,  2, acGUI_Fontsonti24_0043 } /* code 0043 */
  ,{  12,  12,  2, acGUI_Fontsonti24_0061 } /* code 0061 */
  ,{  12,  12,  2, acGUI_Fontsonti24_0065 } /* code 0065 */
  ,{  12,  12,  2, acGUI_Fontsonti24_006E } /* code 006E */
  ,{  12,  12,  2, acGUI_Fontsonti24_006F } /* code 006F */
  ,{  12,  12,  2, acGUI_Fontsonti24_0070 } /* code 0070 */
  ,{  12,  12,  2, acGUI_Fontsonti24_0073 } /* code 0073 */
  ,{  12,  12,  2, acGUI_Fontsonti24_0074 } /* code 0074 */
  ,{  24,  24,  3, acGUI_Fontsonti24_5BB6 } /* code 5BB6 */
  ,{  24,  24,  3, acGUI_Fontsonti24_5C45 } /* code 5C45 */
  ,{  24,  24,  3, acGUI_Fontsonti24_667A } /* code 667A */
  ,{  24,  24,  3, acGUI_Fontsonti24_7A0B } /* code 7A0B */
  ,{  24,  24,  3, acGUI_Fontsonti24_80FD } /* code 80FD */
  ,{  24,  24,  3, acGUI_Fontsonti24_8BA1 } /* code 8BA1 */
  ,{  24,  24,  3, acGUI_Fontsonti24_8BBE } /* code 8BBE */
  ,{  24,  24,  3, acGUI_Fontsonti24_8BFE } /* code 8BFE */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop14 = {
   0x8BFE /* first character */
  ,0x8BFE /* last character  */
  ,&GUI_Fontsonti24_CharInfo[ 16] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop13 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fontsonti24_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontsonti24_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop12 = {
   0x8BA1 /* first character */
  ,0x8BA1 /* last character  */
  ,&GUI_Fontsonti24_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontsonti24_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop11 = {
   0x80FD /* first character */
  ,0x80FD /* last character  */
  ,&GUI_Fontsonti24_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontsonti24_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop10 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_Fontsonti24_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontsonti24_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop9 = {
   0x667A /* first character */
  ,0x667A /* last character  */
  ,&GUI_Fontsonti24_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontsonti24_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop8 = {
   0x5C45 /* first character */
  ,0x5C45 /* last character  */
  ,&GUI_Fontsonti24_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontsonti24_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop7 = {
   0x5BB6 /* first character */
  ,0x5BB6 /* last character  */
  ,&GUI_Fontsonti24_CharInfo[  9] /* address of first character */
  ,&GUI_Fontsonti24_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop6 = {
   0x0073 /* first character */
  ,0x0074 /* last character  */
  ,&GUI_Fontsonti24_CharInfo[  7] /* address of first character */
  ,&GUI_Fontsonti24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop5 = {
   0x006E /* first character */
  ,0x0070 /* last character  */
  ,&GUI_Fontsonti24_CharInfo[  4] /* address of first character */
  ,&GUI_Fontsonti24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop4 = {
   0x0065 /* first character */
  ,0x0065 /* last character  */
  ,&GUI_Fontsonti24_CharInfo[  3] /* address of first character */
  ,&GUI_Fontsonti24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop3 = {
   0x0061 /* first character */
  ,0x0061 /* last character  */
  ,&GUI_Fontsonti24_CharInfo[  2] /* address of first character */
  ,&GUI_Fontsonti24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop2 = {
   0x0043 /* first character */
  ,0x0043 /* last character  */
  ,&GUI_Fontsonti24_CharInfo[  1] /* address of first character */
  ,&GUI_Fontsonti24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsonti24_Prop1 = {
   0x002D /* first character */
  ,0x002D /* last character  */
  ,&GUI_Fontsonti24_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsonti24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsonti24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsonti24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

