/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Auto24.c                                              *
* Font:        宋体                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\新建文本文档.txt *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontAuto24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontAuto24_003A[ 48] = { /* code 003A, COLON */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ________,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontAuto24_5F0F[ 72] = { /* code 5F0F */
  ________,________,________,
  ________,_____X__,________,
  ________,_____XX_,_X______,
  ________,_____XX_,__XX____,
  ________,_____XX_,__XX____,
  ________,_____XX_,___XX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,_____XX_,________,
  ________,_____XX_,________,
  ________,______X_,________,
  ________,______X_,________,
  __XXXXXX,XXXX__X_,________,
  _______X,______X_,________,
  _______X,______XX,________,
  _______X,______XX,________,
  _______X,_______X,________,
  _______X,_______X,X_______,
  _______X,________,X____X__,
  _______X,_XXXX___,XX___X__,
  ______XX,X_______,_XX__X__,
  __XXXX__,________,__XXXX__,
  __XX____,________,___XXX__,
  ________,________,_____XX_,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAuto24_667A[ 72] = { /* code 667A */
  ________,________,________,
  _____X__,________,________,
  _____X__,________,________,
  ____XXXX,XXXX__XX,XXXXX___,
  ____X___,X_____X_,____X___,
  ___X____,X_____X_,____X___,
  ___X___X,X_____X_,____X___,
  __XXXXXX,XXXXXXX_,____X___,
  _______X,______X_,____X___,
  _______X,XX____X_,____X___,
  ______XX,__XX__XX,XXXXX___,
  _____XX_,___XX_X_,____X___,
  ____XX__,___X__X_,________,
  ___X___X,XXXXXXXX,XXX_____,
  __X____X,________,_X______,
  _______X,________,_X______,
  _______X,XXXXXXXX,XX______,
  _______X,________,_X______,
  _______X,________,_X______,
  _______X,________,_X______,
  _______X,XXXXXXXX,XXX_____,
  _______X,________,_XX_____,
  ________,________,_X______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAuto24_6A21[ 72] = { /* code 6A21 */
  ________,________,________,
  _____X__,____X___,_X______,
  _____X__,____XX__,_X______,
  _____X__,____XX__,_X______,
  _____X__,XXXXXXXX,XXXXXX__,
  _____X__,X___XX__,_X______,
  _XXXXXXX,X___XX__,_X______,
  _____X__,___XXXXX,XXXXX___,
  ____XX__,___X____,___X____,
  ____XXX_,___X____,___X____,
  ____XX_X,___XXXXX,XXXX____,
  ___XXX_X,X__X____,___X____,
  ___X_X__,X__X____,___X____,
  ___X_X__,___XXXXX,XXXX____,
  __X__X__,___X__XX,___X____,
  __X__X__,______X_,________,
  _X___X__,XXXXXXXX,XXXXXX__,
  _____X__,______X_,X_______,
  _____X__,_____XX_,X_______,
  _____X__,_____X__,_X______,
  _____X__,____X___,__XX____,
  _____X__,__XX____,___XXXX_,
  _____X__,XX______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAuto24_80FD[ 72] = { /* code 80FD */
  ________,________,________,
  ______X_,________,________,
  ______XX,______XX,________,
  _____XX_,______X_,___X____,
  _____X__,_X____X_,__XXX___,
  ____X___,__X___X_,_XX_____,
  __XX____,XXXX__XX,X_______,
  __XXXXXX,___X__X_,________,
  ________,___X__X_,_____X__,
  ___XXXXX,XXX___X_,_____X__,
  ___XX___,_XX___XX,XXXXXX__,
  ___XX___,_XX_____,________,
  ___XXXXX,XXX__X__,________,
  ___XX___,_XX___X_,___X____,
  ___XX___,_XX___X_,__XXX___,
  ___XX___,_XX___X_,_XX_____,
  ___XXXXX,XXX___XX,X_______,
  ___XX___,_XX___X_,_____X__,
  ___XX___,_XX___X_,_____X__,
  ___XX___,_XX___X_,_____X__,
  ___XX___,_XX___X_,_____XX_,
  ___XX__X,XXX___XX,XXXXXX__,
  ___X____,_X______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAuto24_8282[ 72] = { /* code 8282 */
  ________,________,________,
  ________,________,________,
  ________,X______X,________,
  ________,XX_____X,________,
  ________,XX_____X,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,XX_____X,________,
  ________,XX_____X,________,
  ________,XX_____X,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXX____,
  ________,__X_____,__X_____,
  ________,__X_____,__X_____,
  ________,__X_____,__X_____,
  ________,__X_____,__X_____,
  ________,__X_____,__X_____,
  ________,__X_____,__X_____,
  ________,__X_____,__X_____,
  ________,__X____X,XXX_____,
  ________,__X_____,_XX_____,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAuto24_8C03[ 72] = { /* code 8C03 */
  ________,________,________,
  ________,________,________,
  ____X___,________,________,
  _____X__,__XXXXXX,XXXXXX__,
  _____XX_,__X____X,____X___,
  ______X_,__X____X,____X___,
  ________,__X____X,____X___,
  ________,__X_XXXX,XXX_X___,
  ________,__X____X,____X___,
  _XXXXXX_,__X____X,__X_X___,
  _____X__,__XXXXXX,XXXXX___,
  _____X__,__X_____,____X___,
  _____X__,__X_____,____X___,
  _____X__,__X__XXX,XX__X___,
  _____X__,__X__X__,_X__X___,
  _____X__,__X__X__,_X__X___,
  _____X__,X_X__X__,_X__X___,
  _____X_X,_XX__XXX,XX__X___,
  _____XXX,_X___X__,_X__X___,
  _____XX_,_X______,____X___,
  _____X__,X_______,____X___,
  ________,X_______,_XXXX___,
  _______X,________,___XX___,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontAuto24_CharInfo[7] = {
   {  12,  12,  2, acGUI_FontAuto24_003A } /* code 003A */
  ,{  24,  24,  3, acGUI_FontAuto24_5F0F } /* code 5F0F */
  ,{  24,  24,  3, acGUI_FontAuto24_667A } /* code 667A */
  ,{  24,  24,  3, acGUI_FontAuto24_6A21 } /* code 6A21 */
  ,{  24,  24,  3, acGUI_FontAuto24_80FD } /* code 80FD */
  ,{  24,  24,  3, acGUI_FontAuto24_8282 } /* code 8282 */
  ,{  24,  24,  3, acGUI_FontAuto24_8C03 } /* code 8C03 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontAuto24_Prop7 = {
   0x8C03 /* first character */
  ,0x8C03 /* last character  */
  ,&GUI_FontAuto24_CharInfo[  6] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontAuto24_Prop6 = {
   0x8282 /* first character */
  ,0x8282 /* last character  */
  ,&GUI_FontAuto24_CharInfo[  5] /* address of first character */
  ,&GUI_FontAuto24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontAuto24_Prop5 = {
   0x80FD /* first character */
  ,0x80FD /* last character  */
  ,&GUI_FontAuto24_CharInfo[  4] /* address of first character */
  ,&GUI_FontAuto24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontAuto24_Prop4 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontAuto24_CharInfo[  3] /* address of first character */
  ,&GUI_FontAuto24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontAuto24_Prop3 = {
   0x667A /* first character */
  ,0x667A /* last character  */
  ,&GUI_FontAuto24_CharInfo[  2] /* address of first character */
  ,&GUI_FontAuto24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontAuto24_Prop2 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontAuto24_CharInfo[  1] /* address of first character */
  ,&GUI_FontAuto24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontAuto24_Prop1 = {
   0x003A /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontAuto24_CharInfo[  0] /* address of first character */
  ,&GUI_FontAuto24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontAuto24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontAuto24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

