/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: songti16.c                                            *
* Font:        宋体                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\STM32\精英板 资料盘(A盘)\精英板 资料盘(A盘)\6，软件资料\3，EMWIN学习资料\STM32Cube_FW_F1_V1.0.0\Middlewares\ST\STemWin\Software\Chinese.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002D[ 16] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0043[ 16] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  ____XX__,
  __XX_X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0065[ 16] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _X______,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0070[ 16] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__X__,
  _X_XX___,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0073[ 16] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X______,
  __XXXX__,
  ______X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X__X_,
  ____XX__,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_5BB6[ 32] = { /* code 5BB6 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_______,_____X__,
  _XXXXXXX,XXXXXX__,
  ______X_,________,
  ____XX_X,____X___,
  _XXX___X,X__X____,
  ______X_,X_X_____,
  ____XX__,XX______,
  _XXX___X,X_X_____,
  _____XX_,X__XX___,
  ___XX___,X____XX_,
  XXX___X_,X_______,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_5C45[ 32] = { /* code 5C45 */
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,X_______,
  __X_____,X_______,
  __XXXXXX,XXXXXXX_,
  __X_____,X_______,
  __X_____,X_______,
  __X_XXXX,XXXXX___,
  __X_X___,____X___,
  _X__X___,____X___,
  _X__X___,____X___,
  X___XXXX,XXXXX___,
  ____X___,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_667A[ 32] = { /* code 667A */
  __X_____,________,
  __XXXXX_,_XXXXX__,
  _X__X___,_X___X__,
  ____X___,_X___X__,
  XXXXXXXX,_X___X__,
  ___X_X__,_X___X__,
  __X___X_,_XXXXX__,
  _X______,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_7A0B[ 32] = { /* code 7A0B */
  ____X___,________,
  ___XXX_X,XXXXXX__,
  XXXX___X,_____X__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  XXXXXX_X,XXXXXX__,
  ___X____,________,
  __XX____,________,
  __XXX__X,XXXXXXX_,
  _X_X_X__,__X_____,
  _X_X_X__,__X_____,
  X__X___X,XXXXXX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X__XX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_80FD[ 32] = { /* code 80FD */
  ___X____,_X______,
  __X__X__,_X___X__,
  _X____X_,_X__X___,
  XXXXXXXX,_XXX____,
  _______X,_X______,
  ________,_X____X_,
  _XXXXXX_,_X____X_,
  _X____X_,__XXXXX_,
  _X____X_,________,
  _XXXXXX_,_X___X__,
  _X____X_,_X__X___,
  _X____X_,_XXX____,
  _XXXXXX_,_X______,
  _X____X_,_X____X_,
  _X__X_X_,_X____X_,
  _X___X__,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_8BA1[ 32] = { /* code 8BA1 */
  ________,_X______,
  __X_____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ________,_X______,
  ________,_X______,
  XXXX_XXX,XXXXXXX_,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X_X__,_X______,
  ___XX___,_X______,
  ___X____,_X______,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_8BBE[ 32] = { /* code 8BBE */
  ________,________,
  __X____X,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  _______X,___X____,
  ______X_,____XXX_,
  XXXX_X__,________,
  ___X__XX,XXXXX___,
  ___X___X,____X___,
  ___X___X,___X____,
  ___X____,X__X____,
  ___X_X__,X_X_____,
  ___XX___,_X______,
  ___X____,X_X_____,
  ______XX,___XX___,
  ____XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_8BFE[ 32] = { /* code 8BFE */
  ________,________,
  _X____XX,XXXXX___,
  __X___X_,_X__X___,
  __X___X_,_X__X___,
  ______XX,XXXXX___,
  ______X_,_X__X___,
  XXX___X_,_X__X___,
  __X___XX,XXXXX___,
  __X_____,_X______,
  __X__XXX,XXXXXX__,
  __X_____,XXX_____,
  __X_X__X,_X_X____,
  __XX__X_,_X__X___,
  __X__X__,_X___XX_,
  ________,_X______,
  ________,_X______};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsongti16_CharInfo[17] = {
   {   8,   8,  1, acGUI_Fontsongti16_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_Fontsongti16_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0065 } /* code 0065 */
  ,{   8,   8,  1, acGUI_Fontsongti16_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_Fontsongti16_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_Fontsongti16_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0073 } /* code 0073 */
  ,{   8,   8,  1, acGUI_Fontsongti16_0074 } /* code 0074 */
  ,{  16,  16,  2, acGUI_Fontsongti16_5BB6 } /* code 5BB6 */
  ,{  16,  16,  2, acGUI_Fontsongti16_5C45 } /* code 5C45 */
  ,{  16,  16,  2, acGUI_Fontsongti16_667A } /* code 667A */
  ,{  16,  16,  2, acGUI_Fontsongti16_7A0B } /* code 7A0B */
  ,{  16,  16,  2, acGUI_Fontsongti16_80FD } /* code 80FD */
  ,{  16,  16,  2, acGUI_Fontsongti16_8BA1 } /* code 8BA1 */
  ,{  16,  16,  2, acGUI_Fontsongti16_8BBE } /* code 8BBE */
  ,{  16,  16,  2, acGUI_Fontsongti16_8BFE } /* code 8BFE */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop14 = {
   0x8BFE /* first character */
  ,0x8BFE /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 16] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop13 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontsongti16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop12 = {
   0x8BA1 /* first character */
  ,0x8BA1 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontsongti16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop11 = {
   0x80FD /* first character */
  ,0x80FD /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontsongti16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop10 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontsongti16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop9 = {
   0x667A /* first character */
  ,0x667A /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontsongti16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop8 = {
   0x5C45 /* first character */
  ,0x5C45 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontsongti16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop7 = {
   0x5BB6 /* first character */
  ,0x5BB6 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  9] /* address of first character */
  ,&GUI_Fontsongti16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop6 = {
   0x0073 /* first character */
  ,0x0074 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  7] /* address of first character */
  ,&GUI_Fontsongti16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop5 = {
   0x006E /* first character */
  ,0x0070 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  4] /* address of first character */
  ,&GUI_Fontsongti16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop4 = {
   0x0065 /* first character */
  ,0x0065 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  3] /* address of first character */
  ,&GUI_Fontsongti16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop3 = {
   0x0061 /* first character */
  ,0x0061 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  2] /* address of first character */
  ,&GUI_Fontsongti16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop2 = {
   0x0043 /* first character */
  ,0x0043 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontsongti16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti16_Prop1 = {
   0x002D /* first character */
  ,0x002D /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsongti16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsongti16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

